lenguage: node_js
node_js:
- 13
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  app: nodejs-travis-cicd
  api_key:
    secure: Qq6ZlEjUm32UhD3G3+dH32T2nr0LKnGsSaC6JjhPw9kPi/JB5/gZ2HkbmiQfJSOMMFpv/Pr/aNdqR7Z30OiZIDL7bu1ksRG4l+yyZn3QPpBPiyYrU2nSLmERfJJIpWp9WfaxmC4BXZrUp6xf/LsuKWYo5IwBZg8p788kimNuA6CWvZDQdScwHbzK5Okv3f6PM4r7pJAHBw8gVTHLDKk5ni3yTWftHhJREQOn04HqpeArb1mzEfxuhW5bP815EP0JJpjh4veexhgPM2JAz0cXcUc/ysc3l0fgdybAswa8DiyH+Wg+uavxUpkCB/56UZJyXIlMaGyvUNMgikSnbwpBrdGf+p6YNZ+XyITwpBt6QnfkgF6HNDQxwKp9uQWsd2luqsQ2tWigls7aAhN2rVoN/IlGcrVQqfki/Zq4gYNsxMlxIeqIJTRGNkF9hjaJiwwUz2/GBhzg+Ukc+QBMKCHzkTetDMq3Gbovwf67Z9zV3BYXP36W4Sl+VcwVKZKhEWFmUBQ+dkYw8UjKYmNk6XPvIF2IbsPygFuq2rnhWFRM4gH9dx0ii8OHpIzz4X+zWRF5+nnaP0WNhRpFtw8uGGCGdmpC1FFTWH+1lWs1aeduSEgaVHiaOJmBwtZSJUTNd4DLlEk+JWoXmNKj5tC++/8bSwJMYtd6Wbv4C8MuxRzYH60=
  on:
    branch: master
