lenguage: node_js
node_js:
- 13
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  app: nodejs-travis-cicd
  api_key:
    secure: fOKzXt1lux1bP/D0RmtrVj1SRjJ5Hc2e8Couw8qrihEtSUHGQGWj+UktednMAKIHmGHCXyk418S4XP/zdO4dvnjtOAj4wLzP8ZW6vzO5f/MHjZphL+lwjayoMpSOLCjlLuqqZpARNvsFqlCQL69YZCzZ7VITyHbY7+SLoTQIAtO4jg+YzoJCsKFEJvqGM7K2Hc2k8xi7LZIXKk2N93SMc6yFwUPWbr/4XKawPEyS8TC4sw7U55PifCXhA2QmS9AJ+K+z7bhpvE1qrF2AKMCdpNUmEpwDdRCpctEFN3g/BS9KxxAxiaZCc5MCWZGbRIwbXI9v25HbyEk4n+EnTK4fJPWIEf9d4BwH49G7P4xUwhn1Wb20Xxw9STdz7LYn9ZomHCA4/tnDNwdx3cVSEg4w4MXELSAmmY8w3NlHn5mTRXaGO+yuJkXniTIsM98imYOm8bs2riLLR7FT1UHFzmbYLshdEIAew/kqLJ6A9IBCAR35yxK01LH+t971xkbGwxWXgxMUyl29tgOQeH4kRDWCzlqhfAjNg7pB+l4kPag6FW/7BMNfGumPSTzHYC+Xn6xqyCRvjiHjzdNxRytIHaS3PuaraveMgPCpi05QQQnm6mYeJmUZBRX6Q8KBhC3BUgC83/JZsTZ9TJzHuv8njVQqp9T/QuoneaP5aGh9SqSa+I8=
  on:
    branch: master
