lenguage: node_js
node_js:
- 13
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  app: node-travis-cicd
  api_key:
    secure: gWsf3GvfAWlDoXpzSIf247ygj4TvYlp0gnksky+ACmxDZ0Vkk5jJO+Lf/F3pDap4+Z5lBZVgWaVS0H8ztVdMo45bLsElU/yFWx4vrpAQYKvbPiM4SnRsuDizF+abuF3MyLb7oCDJBq0iC/BxJWF9NfcXIrT2WWYOwBqtOAJmJgHkAG0Kci+woyxZ+TsKp9WAHfWK9LnIkK7AiaFHhDcJZIaWQw3DpZ+Vj0Y0bB0XvRSda/JnvP7WVGUHuwGNwhjW3UJQ55gySYmVgpBhtO2p0wgzfmhDTQqNdKQ6BeD9AqBZcuQQwf4Id9wcO6CHHI0vxbI+HgSuzMETrwwv0Y8GeVj7PmJkbJUOfRqRn5ITtubMdNXM2PMketi4kP6MnFPYWxGeP3MlJ5WtXhhHtXkj5ZfNOHZGis13lj4yWJIEpTDHB3qH76qycpBQxKzUcSCyEx40N9kB6p/UESJ03Ptv8lm7EcCz1STD1vAx6JHChEFpyALzwQ+hQRabTX7kzGwrWk45746nHPcY8h9gfStyndhpya8FP6nrIAjQDWxiJcU1+xUbS4Rds0g1e48FPlHiMADqWr6st1fV8Gx4lcUv7xwZS/yBTtW4HS3WlLF84PHSAVvttxo6pmtsgWT7MPk/HpM+sbx4qo4ZojUdfmYQdIxYjnaNVUlV5bTlOrQqNa8=
