lenguage: node_js
node_js:
  - 13
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
    secure: rKu1XwG6BSC18v6M1UHzdzdeyHLgoDSxZS0BP3V+apwbH79U1nSGCQ+qbXSivsKLm5Hrox0no30/OT0kW6fgEEu/IcJbqlV8bcqxYunrlw6tmRdkVZh7R2YMnaS0VImaylDnIb1QFAKNkRaXU5s2BAjCADXk6HpopPx9mz+g9hYStgEYk3ad9EjP2K+h1VvTF6u//19jsFHiPblKNbh99QK2BPXFtokqDQHrRZPXwTsaQhueNwHfoO84OP170P/A1B1eKLyo3L9MpoHqLwTlMLHCAzuZmteT7bjFizao50Y6skPLAxnOXIFCRwzrwQq4/4rXU2nblPpX1vh4mQVwc0YZa0JEK0b4s8dmG+jE5g8QA363EQvVb3FcJJX1IRRJFIYzejyvbNVnisxnuKIkyZo6sDiiV0mFQEd5nYfK8X0ZRq9EaUkACTz/NcCT+0eTXAIlwu5EtcI+i5IS4f/s6qFkdXe/REAzKwKRgm3ad5zejJZdUpxVur+HihV8+2wv2mmRP6ntnBItWWP5LBq0iQluYjQ9GXi+bhOLyIhNPeXhh765o2TJPBZLkr+E0L2jmEoxYOq0rd9ZDHjTogJyXn0SeGJ6tYduij/d+2ZTvlEPF/tCQXzJ2l/I+oMVEW2lbxoahdmYlP3ehocdMY/sOy1MvwUuEJIkd3NV+gn5M2s=
  app: node-travis-cicd
  on:
    repo: daniloabella18/node-travis-cicd
  skip_cleanup: "true"
