lenguage: node_js
node_js:
  - 13
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
  - npm i fsevents@latest -f --save-optional

deploy:
  provider: heroku
  app: nodejs-travis-cicd
  api_key:
    secure: yx7VuFJb3vFLzgRpZJSPpO7fjWxPuWEC3WaJNUSo9e0EQ39JGhQGS+k66SA3NX1U/9fvqC45ZtQnA+zVrAdvPnEHn1OgxUhKhin72rGBWLs97XLDU440w6tVTH88ghkvw4Klpfn8nAq26a0a0Gi9iQhP9OQKxVHGBWBF0VHJ2ewf1YTFO9smFiZxBHMh8Q1UIj4qbqziOQTWu5P2hy4ska/azGf3PRRazbqNIbRM7W0+EhLuO3Shk/el6WqWwB68bw8iqRAKh6gLkoC+eQ9D8bPD2WgB/vvpD1Zei/xrdNtVdFtvid1OYDwXLKFmBJQXDgFsg+oHe1LVbyGf1oucOSVh2OhMVrXATx+yGj0WMvCsMsChc2f3GsGWf2b6ucoY64zFXt4xMAkJsGTowihb9U6joDNpV2kgorBt/Z+LqvC48PlpAKWZCzVQjVxlUsCb9n4IPNvWsVdUWkAA75BwD2xK3T6o9pxzfLTdBZ6jEY2dhXXSvu5I8F7iK8Q1bJx8YepoC/gYvl6r628C7JnTTcLhP5gsDwBnRzm2l4T5h7mAHRxypH7g7QUBmG/Fm9HxGN5aS+8JY75LsaORRhHBx2hFMsirCZvLYUGFSnXw3s+d3ignN3VBGcCRCabWCJK7X3TlPWw7td7FgrF09K4YxgFIby3N4pacGcDpY8W+mUU=
