lenguage: node_js
node_js:
  - 13
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  app: nodejs-travis-cicd
  api_key:
    secure: OL18b/13BU/+iiKCsYYa+4y19OWmEVjURpdPUiF7226ANSLvH9plRaLx+fp7OYdsSmxhnWOWzDWpaiwkvbJ+sHE0rcrFdhIW4zQelo1w1KWtXSfAhj+ee1FJR2yAcmx6hDUdDEa6wgz2MegRkjya7JUDO0sLEmvdxKmDSzZi8ZG0om7kt/8fYsK3XwcivkH2ZWLg4LGj9cu8qX80OkhnE+SExrMu1REi14CkKPpWal9b/LxydApB3tuxf6xxCCXnJhEMbunPx6iINPOI4JaFpCVog3vWAfWWpwUNlmhbS65sawtSst6FxdUk7uRPDPu+bEkGA9NhvgfOpEr/kdCFqkunF6S8w6N1VP9uE29VSuE4M/jDUK2pYidM9YNk4onPl6Bobgg+LmfoQExbpjw0HRd22ejeH9mwZtERxjll4QDvqupJ5fspkhYmx5m2ZVyhSaBSNzjMrh1m3J0bST0oUxqjxJY6KJbtK3IAmrWESCjZRChspQWtgjkBvrP11ziWtporOiBTOd+IoUJRFtDI6ZnVRvEHoXOfAR7ebN2B+GcH9zUG/MMN7QkwpO4jgg7O/e9EhLiAO44bFSDmSw4RyzFgDPMudKyWO7b7ya9ltJ7aePnaOTocFExAgsvEV93zFseLZezLGO1ypCrUD38jwePkzZav8RlfbGepjuKYozI=
  skip_cleanup: true
  on:
    repo: daniloabella18/node-travis-cicd
